### ISSUE TITLE
CloudFormation CREATE_FAILED

### ISSUE THREAD

**Issue by ericpardee** [concurrencylabs/locust-cloudwatch#3]
When using the CloudWatch template, received 
AWS::EC2::Instance 
LocustServer 
Failed to receive 1 resource signal(s) within the specified duration

In looking in /var/log/cfn-init.log:
`2018-10-14 04:41:54,206 [DEBUG] Running command install_locust
2018-10-14 04:41:54,206 [DEBUG] No test for command install_locust
2018-10-14 04:41:56,161 [ERROR] Command install_locust (pip install locustio) failed
2018-10-14 04:41:56,161 [DEBUG] Command install_locust output: You are using pip version 6.1.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting locustio
  Downloading https://files.pythonhosted.org/packages/89/11/4297775bd82b0b0ad863bf150bd6090833e37c0a98eed838385288b6ec37/locustio-0.9.0-py2.py3-none-any.whl (237kB)
Collecting requests>=2.9.1 (from locustio)
  Downloading https://files.pythonhosted.org/packages/65/47/7e02164a2a3db50ed6d8a6ab1d6d60b69c4c3fdf57a284257925dfc12bda/requests-2.19.1-py2.py3-none-any.whl (91kB)
Collecting gevent>=1.2.2 (from locustio)
  Downloading https://files.pythonhosted.org/packages/10/c1/9499b146bfa43aa4f1e0ed1bab1bd3209a4861d25650c11725036c731cf5/gevent-1.3.7.tar.gz (4.6MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-ncdAMv/gevent/setup.py", line 418, in <module>
        run_setup(EXT_MODULES, run_make=_BUILDING)
      File "/tmp/pip-build-ncdAMv/gevent/setup.py", line 402, in run_setup
        "signal_os_incompat = gevent.monkey:_subscribe_signal_os",
      File "/usr/lib64/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 265, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 310, in fetch_build_eggs
        replace_conflicting=True,
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 767, in resolve
        requirements = list(requirements)[::-1]
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2876, in parse_requirements
        "version spec")
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2852, in scan_list
        raise ValueError(msg, line, "at", line[p:])
    ValueError: ("Expected ',' or end-of-list in", "cffi >= 1.11.5 ; sys_platform == 'win32' and platform_python_implementation == 'CPython'", 'at', " ; sys_platform == 'win32' and platform_python_implementation == 'CPython'")

    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ncdAMv/gevent

2018-10-14 04:41:56,161 [ERROR] Error encountered during build of install_packages: Command install_locust failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command install_locust failed
2018-10-14 04:41:56,163 [ERROR] -----------------------BUILD FAILED!------------------------
2018-10-14 04:41:56,165 [ERROR] Unhandled exception during build: Command install_locust failed
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 260, in build
    changes['commands'] = CommandTool().apply(self._config.commands)
  File "/usr/lib/python2.7/dist-packages/cfnbootstrap/command_tool.py", line 117, in apply
    raise ToolError(u"Command %s failed" % name)
ToolError: Command install_locust failed`

In manually trying to install locustio, got:
Cannot uninstall 'chardet'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

This solved that install issue:
https://stackoverflow.com/questions/49915951/cannot-uninstall-chardet

So I added commands:
            c_upgrade_pip:
              command: "pip install --upgrade pip"
            b_remove_that:
              command: "rm -r /usr/lib/python2.7/dist-packages/chardet"
            a_remove_this:
              command: "rm /usr/lib/python2.7/dist-packages/chardet-2.0.1.egg-info"

Then it failed:
2018-10-14 06:06:26,453 [DEBUG] Command install_boto3 output: /bin/sh: pip: command not found

So I prefaced pip commands with /usr/local/bin/ and the template worked..

https://github.com/concurrencylabs/locust-cloudwatch/pull/2

**Comment by concurrencylabs** [comment]
Thank you for reporting this issue and for the pull request. We're looking at it now.

**Comment by concurrencylabs** [comment]
We took a look at the existing template and it turns out the AMI specified in it was too old. We updated the CloudFormation template with the latest available AMI and that solved the issue: 

https://github.com/concurrencylabs/locust-cloudwatch/commit/9ef6014f51eed6c3c361b8167818cd03dd4ecfbc#diff-090b163010c3fe6177a59f4c6f364934

Thanks again for reporting this issue.
